### ISSUE TITLE
5.5.3 introduced freeze on iOS when enabling flight mode

### ISSUE THREAD

**Issue by CliffCawley** [MindscapeHQ/raygun4net#372] opened 2018-01-10 23:00 UTC
5.5.3 when you're on iOS and you activate flight mode it freezes (locks ui) our xamarin forms app for up to a couple of minutes.

Downgrading to 5.5.2 'fixes' the issue for us so something in 5.5.3 has caused this.

**Comment by tougher** [comment] 2018-02-21 13:42
I have the same issue - spend 1.5 day taking my app apart until I removed AttachPulse() and the freezing went away.
If you're lucky, you sometimes can pause the debugger while the freezing is happening, and you'll see http calls on main thread?!? This is really really bad.

**Comment by tougher** [comment] 2018-02-21 13:43
It's of cause not only related to flight-mode, but bad network connections in general (WiFi not connected to the internet in my case).

**Comment by QuantumNightmare** [comment] 2018-02-21 19:29
Hi CliffCawley and tougher,

My apologies for not updating this issue. This freeze has been resolved in the latest version of Raygun4Net v5.5.4. The freeze was caused by certain requests to Raygun being synchronous. This has been resolved by updating all requests to being asynchronous.

**Closed by QuantumNightmare** 2018-02-21 19:29 UTC
